version: "3.7"

services:
  captain_mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - DB_USERNAME=${MONGO_USERNAME}
      - DB_PASSWORD=${MONGO_PASSWORD}

  captain_mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - captain_mongodb
    depends_on:
      - captain_mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=captain_mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
    env_file:
      - .env
